# Generated by Django 3.2.15 on 2023-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Student ID')),
                ('student_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Student Name')),
                ('academic_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Academic Level')),
                ('first_companion', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Companion')),
                ('second_companion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Companion')),
                ('invite_image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
