# Generated by Django 3.2.15 on 2023-06-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
