# Generated by Django 3.2.15 on 2023-06-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0002_alter_invite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={},
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='link',
        ),
        migrations.AddField(
            model_name='invite',
            name='first_companion_invite_image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invite',
            name='first_companion_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Companion number'),
        ),
        migrations.AddField(
            model_name='invite',
            name='first_companion_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_image_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invite',
            name='link1',
            field=models.URLField(blank=True, null=True, verbose_name='Link1'),
        ),
        migrations.AddField(
            model_name='invite',
            name='link2',
            field=models.URLField(blank=True, null=True, verbose_name='Link2'),
        ),
        migrations.AddField(
            model_name='invite',
            name='link3',
            field=models.URLField(blank=True, null=True, verbose_name='Link3'),
        ),
        migrations.AddField(
            model_name='invite',
            name='second_companion_invite_image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='invite',
            name='second_companion_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Companion number'),
        ),
        migrations.AddField(
            model_name='invite',
            name='second_companion_read',
            field=models.BooleanField(default=False),
        ),
    ]
