# Generated by Django 3.2.15 on 2023-06-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0003_auto_20230603_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='first_companion_invite_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='invite',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='second_companion_invite_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
